//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITI.EVO.Proxies.CuratioCommon {
    using System;
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="AreaTypesEnum", Namespace="http://schemas.datacontract.org/2004/07/MIS.Common.Svc.Enums")]
    public enum AreaTypesEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Region = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Municipality = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MunicipalCenter = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Village = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Country = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Town = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecordTypesEnum", Namespace="http://schemas.datacontract.org/2004/07/MIS.Common.Svc.Enums")]
    public enum RecordTypesEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AreaContract", Namespace="http://schemas.datacontract.org/2004/07/MIS.Common.Svc.Contracts")]
    [System.SerializableAttribute()]
    public partial class AreaContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CITI.EVO.Proxies.CuratioCommon.AreaTypeContract AreaTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CraCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EngNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> OLD_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CITI.EVO.Proxies.CuratioCommon.AreaContract ParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CITI.EVO.Proxies.CuratioCommon.PhoneIndexContract[] PhoneIndexesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CITI.EVO.Proxies.CuratioCommon.RecordTypesEnum RecordTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CITI.EVO.Proxies.CuratioCommon.AreaTypeContract AreaType {
            get {
                return this.AreaTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaTypeField, value) != true)) {
                    this.AreaTypeField = value;
                    this.RaisePropertyChanged("AreaType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CraCode {
            get {
                return this.CraCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CraCodeField, value) != true)) {
                    this.CraCodeField = value;
                    this.RaisePropertyChanged("CraCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateChanged {
            get {
                return this.DateChangedField;
            }
            set {
                if ((this.DateChangedField.Equals(value) != true)) {
                    this.DateChangedField = value;
                    this.RaisePropertyChanged("DateChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDeleted {
            get {
                return this.DateDeletedField;
            }
            set {
                if ((this.DateDeletedField.Equals(value) != true)) {
                    this.DateDeletedField = value;
                    this.RaisePropertyChanged("DateDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EngName {
            get {
                return this.EngNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EngNameField, value) != true)) {
                    this.EngNameField = value;
                    this.RaisePropertyChanged("EngName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeoName {
            get {
                return this.GeoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GeoNameField, value) != true)) {
                    this.GeoNameField = value;
                    this.RaisePropertyChanged("GeoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewCode {
            get {
                return this.NewCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NewCodeField, value) != true)) {
                    this.NewCodeField = value;
                    this.RaisePropertyChanged("NewCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> OLD_ID {
            get {
                return this.OLD_IDField;
            }
            set {
                if ((this.OLD_IDField.Equals(value) != true)) {
                    this.OLD_IDField = value;
                    this.RaisePropertyChanged("OLD_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CITI.EVO.Proxies.CuratioCommon.AreaContract Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentField, value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((this.ParentIDField.Equals(value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CITI.EVO.Proxies.CuratioCommon.PhoneIndexContract[] PhoneIndexes {
            get {
                return this.PhoneIndexesField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneIndexesField, value) != true)) {
                    this.PhoneIndexesField = value;
                    this.RaisePropertyChanged("PhoneIndexes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CITI.EVO.Proxies.CuratioCommon.RecordTypesEnum RecordType {
            get {
                return this.RecordTypeField;
            }
            set {
                if ((this.RecordTypeField.Equals(value) != true)) {
                    this.RecordTypeField = value;
                    this.RaisePropertyChanged("RecordType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TypeID {
            get {
                return this.TypeIDField;
            }
            set {
                if ((this.TypeIDField.Equals(value) != true)) {
                    this.TypeIDField = value;
                    this.RaisePropertyChanged("TypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AreaTypeContract", Namespace="http://schemas.datacontract.org/2004/07/MIS.Common.Svc.Contracts")]
    [System.SerializableAttribute()]
    public partial class AreaTypeContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EngNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateChanged {
            get {
                return this.DateChangedField;
            }
            set {
                if ((this.DateChangedField.Equals(value) != true)) {
                    this.DateChangedField = value;
                    this.RaisePropertyChanged("DateChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDeleted {
            get {
                return this.DateDeletedField;
            }
            set {
                if ((this.DateDeletedField.Equals(value) != true)) {
                    this.DateDeletedField = value;
                    this.RaisePropertyChanged("DateDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EngName {
            get {
                return this.EngNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EngNameField, value) != true)) {
                    this.EngNameField = value;
                    this.RaisePropertyChanged("EngName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeoName {
            get {
                return this.GeoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GeoNameField, value) != true)) {
                    this.GeoNameField = value;
                    this.RaisePropertyChanged("GeoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneIndexContract", Namespace="http://schemas.datacontract.org/2004/07/MIS.Common.Svc.Contracts")]
    [System.SerializableAttribute()]
    public partial class PhoneIndexContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CITI.EVO.Proxies.CuratioCommon.PhoneIndexTypeContract PhoneIndexTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateChanged {
            get {
                return this.DateChangedField;
            }
            set {
                if ((this.DateChangedField.Equals(value) != true)) {
                    this.DateChangedField = value;
                    this.RaisePropertyChanged("DateChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDeleted {
            get {
                return this.DateDeletedField;
            }
            set {
                if ((this.DateDeletedField.Equals(value) != true)) {
                    this.DateDeletedField = value;
                    this.RaisePropertyChanged("DateDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CITI.EVO.Proxies.CuratioCommon.PhoneIndexTypeContract PhoneIndexType {
            get {
                return this.PhoneIndexTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneIndexTypeField, value) != true)) {
                    this.PhoneIndexTypeField = value;
                    this.RaisePropertyChanged("PhoneIndexType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneIndexTypeContract", Namespace="http://schemas.datacontract.org/2004/07/MIS.Common.Svc.Contracts")]
    [System.SerializableAttribute()]
    public partial class PhoneIndexTypeContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateChanged {
            get {
                return this.DateChangedField;
            }
            set {
                if ((this.DateChangedField.Equals(value) != true)) {
                    this.DateChangedField = value;
                    this.RaisePropertyChanged("DateChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDeleted {
            get {
                return this.DateDeletedField;
            }
            set {
                if ((this.DateDeletedField.Equals(value) != true)) {
                    this.DateDeletedField = value;
                    this.RaisePropertyChanged("DateDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MobileIndexesContract", Namespace="http://schemas.datacontract.org/2004/07/MIS.Common.Svc.Contracts")]
    [System.SerializableAttribute()]
    public partial class MobileIndexesContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EngOperatorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeoOperatorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateChanged {
            get {
                return this.DateChangedField;
            }
            set {
                if ((this.DateChangedField.Equals(value) != true)) {
                    this.DateChangedField = value;
                    this.RaisePropertyChanged("DateChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDeleted {
            get {
                return this.DateDeletedField;
            }
            set {
                if ((this.DateDeletedField.Equals(value) != true)) {
                    this.DateDeletedField = value;
                    this.RaisePropertyChanged("DateDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EngOperatorName {
            get {
                return this.EngOperatorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EngOperatorNameField, value) != true)) {
                    this.EngOperatorNameField = value;
                    this.RaisePropertyChanged("EngOperatorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeoOperatorName {
            get {
                return this.GeoOperatorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GeoOperatorNameField, value) != true)) {
                    this.GeoOperatorNameField = value;
                    this.RaisePropertyChanged("GeoOperatorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LanguageContract", Namespace="http://schemas.datacontract.org/2004/07/MIS.Common.Svc.Contracts")]
    [System.SerializableAttribute()]
    public partial class LanguageContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EngNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NativeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PairField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateChanged {
            get {
                return this.DateChangedField;
            }
            set {
                if ((this.DateChangedField.Equals(value) != true)) {
                    this.DateChangedField = value;
                    this.RaisePropertyChanged("DateChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDeleted {
            get {
                return this.DateDeletedField;
            }
            set {
                if ((this.DateDeletedField.Equals(value) != true)) {
                    this.DateDeletedField = value;
                    this.RaisePropertyChanged("DateDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EngName {
            get {
                return this.EngNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EngNameField, value) != true)) {
                    this.EngNameField = value;
                    this.RaisePropertyChanged("EngName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NativeName {
            get {
                return this.NativeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NativeNameField, value) != true)) {
                    this.NativeNameField = value;
                    this.RaisePropertyChanged("NativeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pair {
            get {
                return this.PairField;
            }
            set {
                if ((object.ReferenceEquals(this.PairField, value) != true)) {
                    this.PairField = value;
                    this.RaisePropertyChanged("Pair");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CuratioCommon.ICommonDataWcf")]
    public interface ICommonDataWcf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/DoWork", ReplyAction="http://tempuri.org/ICommonDataWcf/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/DoWork", ReplyAction="http://tempuri.org/ICommonDataWcf/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetAreas", ReplyAction="http://tempuri.org/ICommonDataWcf/GetAreasResponse")]
        CITI.EVO.Proxies.CuratioCommon.AreaContract[] GetAreas(CITI.EVO.Proxies.CuratioCommon.AreaTypesEnum type, CITI.EVO.Proxies.CuratioCommon.RecordTypesEnum recordType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetAreas", ReplyAction="http://tempuri.org/ICommonDataWcf/GetAreasResponse")]
        System.Threading.Tasks.Task<CITI.EVO.Proxies.CuratioCommon.AreaContract[]> GetAreasAsync(CITI.EVO.Proxies.CuratioCommon.AreaTypesEnum type, CITI.EVO.Proxies.CuratioCommon.RecordTypesEnum recordType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetChildAreas", ReplyAction="http://tempuri.org/ICommonDataWcf/GetChildAreasResponse")]
        CITI.EVO.Proxies.CuratioCommon.AreaContract[] GetChildAreas(System.Guid ParentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetChildAreas", ReplyAction="http://tempuri.org/ICommonDataWcf/GetChildAreasResponse")]
        System.Threading.Tasks.Task<CITI.EVO.Proxies.CuratioCommon.AreaContract[]> GetChildAreasAsync(System.Guid ParentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetAreaByID", ReplyAction="http://tempuri.org/ICommonDataWcf/GetAreaByIDResponse")]
        CITI.EVO.Proxies.CuratioCommon.AreaContract GetAreaByID(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetAreaByID", ReplyAction="http://tempuri.org/ICommonDataWcf/GetAreaByIDResponse")]
        System.Threading.Tasks.Task<CITI.EVO.Proxies.CuratioCommon.AreaContract> GetAreaByIDAsync(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetAreaByCode", ReplyAction="http://tempuri.org/ICommonDataWcf/GetAreaByCodeResponse")]
        CITI.EVO.Proxies.CuratioCommon.AreaContract GetAreaByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetAreaByCode", ReplyAction="http://tempuri.org/ICommonDataWcf/GetAreaByCodeResponse")]
        System.Threading.Tasks.Task<CITI.EVO.Proxies.CuratioCommon.AreaContract> GetAreaByCodeAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetAllMobileIndexes", ReplyAction="http://tempuri.org/ICommonDataWcf/GetAllMobileIndexesResponse")]
        CITI.EVO.Proxies.CuratioCommon.MobileIndexesContract[] GetAllMobileIndexes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetAllMobileIndexes", ReplyAction="http://tempuri.org/ICommonDataWcf/GetAllMobileIndexesResponse")]
        System.Threading.Tasks.Task<CITI.EVO.Proxies.CuratioCommon.MobileIndexesContract[]> GetAllMobileIndexesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetMobileIndexByID", ReplyAction="http://tempuri.org/ICommonDataWcf/GetMobileIndexByIDResponse")]
        CITI.EVO.Proxies.CuratioCommon.MobileIndexesContract GetMobileIndexByID(System.Nullable<System.Guid> ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetMobileIndexByID", ReplyAction="http://tempuri.org/ICommonDataWcf/GetMobileIndexByIDResponse")]
        System.Threading.Tasks.Task<CITI.EVO.Proxies.CuratioCommon.MobileIndexesContract> GetMobileIndexByIDAsync(System.Nullable<System.Guid> ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetLanguages", ReplyAction="http://tempuri.org/ICommonDataWcf/GetLanguagesResponse")]
        CITI.EVO.Proxies.CuratioCommon.LanguageContract[] GetLanguages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetLanguages", ReplyAction="http://tempuri.org/ICommonDataWcf/GetLanguagesResponse")]
        System.Threading.Tasks.Task<CITI.EVO.Proxies.CuratioCommon.LanguageContract[]> GetLanguagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetTranslatedText", ReplyAction="http://tempuri.org/ICommonDataWcf/GetTranslatedTextResponse")]
        string GetTranslatedText(string moduleName, string languagePair, string key, string defaultText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/GetTranslatedText", ReplyAction="http://tempuri.org/ICommonDataWcf/GetTranslatedTextResponse")]
        System.Threading.Tasks.Task<string> GetTranslatedTextAsync(string moduleName, string languagePair, string key, string defaultText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/SetTranslatedText", ReplyAction="http://tempuri.org/ICommonDataWcf/SetTranslatedTextResponse")]
        void SetTranslatedText(string moduleName, string languagePair, string key, string translatedText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/SetTranslatedText", ReplyAction="http://tempuri.org/ICommonDataWcf/SetTranslatedTextResponse")]
        System.Threading.Tasks.Task SetTranslatedTextAsync(string moduleName, string languagePair, string key, string translatedText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/SendSmsm", ReplyAction="http://tempuri.org/ICommonDataWcf/SendSmsmResponse")]
        bool SendSmsm(string number, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonDataWcf/SendSmsm", ReplyAction="http://tempuri.org/ICommonDataWcf/SendSmsmResponse")]
        System.Threading.Tasks.Task<bool> SendSmsmAsync(string number, string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonDataWcfChannel : CITI.EVO.Proxies.CuratioCommon.ICommonDataWcf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonDataWcfClient : System.ServiceModel.ClientBase<CITI.EVO.Proxies.CuratioCommon.ICommonDataWcf>, CITI.EVO.Proxies.CuratioCommon.ICommonDataWcf {
        
        public CommonDataWcfClient() {
        }
        
        public CommonDataWcfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonDataWcfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonDataWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonDataWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public CITI.EVO.Proxies.CuratioCommon.AreaContract[] GetAreas(CITI.EVO.Proxies.CuratioCommon.AreaTypesEnum type, CITI.EVO.Proxies.CuratioCommon.RecordTypesEnum recordType) {
            return base.Channel.GetAreas(type, recordType);
        }
        
        public System.Threading.Tasks.Task<CITI.EVO.Proxies.CuratioCommon.AreaContract[]> GetAreasAsync(CITI.EVO.Proxies.CuratioCommon.AreaTypesEnum type, CITI.EVO.Proxies.CuratioCommon.RecordTypesEnum recordType) {
            return base.Channel.GetAreasAsync(type, recordType);
        }
        
        public CITI.EVO.Proxies.CuratioCommon.AreaContract[] GetChildAreas(System.Guid ParentID) {
            return base.Channel.GetChildAreas(ParentID);
        }
        
        public System.Threading.Tasks.Task<CITI.EVO.Proxies.CuratioCommon.AreaContract[]> GetChildAreasAsync(System.Guid ParentID) {
            return base.Channel.GetChildAreasAsync(ParentID);
        }
        
        public CITI.EVO.Proxies.CuratioCommon.AreaContract GetAreaByID(System.Guid Id) {
            return base.Channel.GetAreaByID(Id);
        }
        
        public System.Threading.Tasks.Task<CITI.EVO.Proxies.CuratioCommon.AreaContract> GetAreaByIDAsync(System.Guid Id) {
            return base.Channel.GetAreaByIDAsync(Id);
        }
        
        public CITI.EVO.Proxies.CuratioCommon.AreaContract GetAreaByCode(string code) {
            return base.Channel.GetAreaByCode(code);
        }
        
        public System.Threading.Tasks.Task<CITI.EVO.Proxies.CuratioCommon.AreaContract> GetAreaByCodeAsync(string code) {
            return base.Channel.GetAreaByCodeAsync(code);
        }
        
        public CITI.EVO.Proxies.CuratioCommon.MobileIndexesContract[] GetAllMobileIndexes() {
            return base.Channel.GetAllMobileIndexes();
        }
        
        public System.Threading.Tasks.Task<CITI.EVO.Proxies.CuratioCommon.MobileIndexesContract[]> GetAllMobileIndexesAsync() {
            return base.Channel.GetAllMobileIndexesAsync();
        }
        
        public CITI.EVO.Proxies.CuratioCommon.MobileIndexesContract GetMobileIndexByID(System.Nullable<System.Guid> ID) {
            return base.Channel.GetMobileIndexByID(ID);
        }
        
        public System.Threading.Tasks.Task<CITI.EVO.Proxies.CuratioCommon.MobileIndexesContract> GetMobileIndexByIDAsync(System.Nullable<System.Guid> ID) {
            return base.Channel.GetMobileIndexByIDAsync(ID);
        }
        
        public CITI.EVO.Proxies.CuratioCommon.LanguageContract[] GetLanguages() {
            return base.Channel.GetLanguages();
        }
        
        public System.Threading.Tasks.Task<CITI.EVO.Proxies.CuratioCommon.LanguageContract[]> GetLanguagesAsync() {
            return base.Channel.GetLanguagesAsync();
        }
        
        public string GetTranslatedText(string moduleName, string languagePair, string key, string defaultText) {
            return base.Channel.GetTranslatedText(moduleName, languagePair, key, defaultText);
        }
        
        public System.Threading.Tasks.Task<string> GetTranslatedTextAsync(string moduleName, string languagePair, string key, string defaultText) {
            return base.Channel.GetTranslatedTextAsync(moduleName, languagePair, key, defaultText);
        }
        
        public void SetTranslatedText(string moduleName, string languagePair, string key, string translatedText) {
            base.Channel.SetTranslatedText(moduleName, languagePair, key, translatedText);
        }
        
        public System.Threading.Tasks.Task SetTranslatedTextAsync(string moduleName, string languagePair, string key, string translatedText) {
            return base.Channel.SetTranslatedTextAsync(moduleName, languagePair, key, translatedText);
        }
        
        public bool SendSmsm(string number, string text) {
            return base.Channel.SendSmsm(number, text);
        }
        
        public System.Threading.Tasks.Task<bool> SendSmsmAsync(string number, string text) {
            return base.Channel.SendSmsmAsync(number, text);
        }
    }
}
